import type { Metadata } from "next";
import { Radio_Canada } from "next/font/google";
import "./globals.css";

const inter = Radio_Canada({ weight: ["400", "500", "600",  "700"], subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Sign in | Lichess Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>

  );
}
